# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-03 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funrun_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='matches',
            field=models.ManyToManyField(blank=True, to='funrun_history.Match'),
        ),
    ]
